<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-28T18:06:28 IST" name="Default suite" finished-at="2022-03-28T18:08:57 IST" duration-ms="149002">
    <groups>
    </groups>
    <test started-at="2022-03-28T18:06:28 IST" name="Default test" finished-at="2022-03-28T18:08:57 IST" duration-ms="149002">
      <class name="Mobile.MyCards">
        <test-method is-config="true" signature="report()[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:06:28 IST" name="report" finished-at="2022-03-28T18:06:28 IST" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method is-config="true" signature="appium_server_running()[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:06:28 IST" name="appium_server_running" finished-at="2022-03-28T18:06:38 IST" duration-ms="9897" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appium_server_running -->
        <test-method signature="MyCardssection()[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:06:38 IST" name="MyCardssection" finished-at="2022-03-28T18:08:27 IST" duration-ms="108639" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[invalid card details are entered expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: invalid card details are entered expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Mobile.MyCards.MyCardssection(MyCards.java:159)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyCardssection -->
        <test-method is-config="true" signature="appium_server_stop(org.testng.ITestResult)[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:08:27 IST" name="appium_server_stop" finished-at="2022-03-28T18:08:39 IST" duration-ms="12479" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=MyCardssection status=FAILURE method=MyCards.MyCardssection()[pri:0, instance:Mobile.MyCards@d9345cd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appium_server_stop -->
        <test-method is-config="true" signature="reportEmail()[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:08:39 IST" name="reportEmail" finished-at="2022-03-28T18:08:57 IST" duration-ms="17961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportEmail -->
        <test-method is-config="true" signature="flush()[pri:0, instance:Mobile.MyCards@d9345cd]" started-at="2022-03-28T18:08:57 IST" name="flush" finished-at="2022-03-28T18:08:57 IST" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- Mobile.MyCards -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
